try {
    alert('Action completed!');
    alert('Action completed!');
    data.push(value);
} catch (error) {
    console.error("Error:", error);
}